version: "3.11"

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5439:5432"
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  bot:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - postgres

volumes:
  postgres-data: {}
