[Project]
name = "Personality"
version = "0.1.0"
description = "Volunteer bot"
authors = ["Th3Kanashii"]

repository = "https://github.com/Th3Kanashii/telegram-volunteer-bot"
license = "MIT"

[tool.black]
line_length = 99
exclude = "venv/"

[tool.ruff]
target-version = "py39"
line-length = 99
select = [
    "C",
    "DTZ",
    "E",
    "F",
    "I",
    "ICN",
    "ISC",
    "N",
    "PLC",
    "PLE",
    "Q",
    "S",
    "T",
    "W",
    "YTT",
    "RET",
    "SIM",
    "ASYNC",
]
exclude = [
    ".git",
    ".venv",
    ".idea",
    ".cache",
]
ignore = [
    "T201",
    "S101",
    "S106",
    "DTZ001",
    "DTZ005",
    "DTZ007",
]

[tool.mypy]
plugins = [
    "sqlalchemy.ext.mypy.plugin",
]
exclude = [
    ".git",
    ".venv",
    ".idea",
    ".cache",
]

[[tool.mypy.overrides]]
module = ["bot.handlers.*"]
strict_optional = false
warn_return_any = false
