"""create_table

Revision ID: 001
Revises:
Create Date: 2024-03-24 23:13:26.164139

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("topics",
    sa.Column("id", sa.BigInteger(), nullable=False),
    sa.Column("youth_policy_topic", sa.INTEGER(), nullable=True),
    sa.Column("psychologist_support_topic", sa.INTEGER(), nullable=True),
    sa.Column("legal_support_topic", sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("users",
    sa.Column("id", sa.BigInteger(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("locale", sa.String(length=2), nullable=False),
    sa.Column("youth_policy", sa.Boolean(), nullable=False),
    sa.Column("psychologist_support", sa.Boolean(), nullable=False),
    sa.Column("civic_education", sa.Boolean(), nullable=False),
    sa.Column("legal_support", sa.Boolean(), nullable=False),
    sa.Column("active_category", sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("topics")
    # ### end Alembic commands ###
